### ISSUE TITLE
Can't change blog name or update with mysql back-end

### ISSUE THREAD

**Issue by scrummie02** [rxtur/BlogEngine.NET#8]
I've gotten into the dashboard and I can't save anything I get update failed.  Plus some actions like saving the name of the blog won't occur when hitting save.

**Comment by rxtur** [comment]
Do you see any errors in the log or javascript console? I don't have this issue on my local install.

**Comment by scrummie02** [comment]
Application information: 
    Application domain: /LM/W3SVC/1/ROOT-1-130910834832721816 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: C:\inetpub\wwwroot\ 
    Machine name: ATHENA 
 
Process information: 
    Process ID: 5020 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\DefaultAppPool 
 
Exception information: 
    Exception type: HttpException 
    Exception message: Path '/admin/index.cshtml' is forbidden.
   at System.Web.HttpForbiddenHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: http://www.site.com/admin/index.cshtml 
    Request path: /admin/index.cshtml 
    User host address: 192.168.200.104 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\DefaultAppPool 
 
Thread information: 
    Thread ID: 52 
    Thread account name: IIS APPPOOL\DefaultAppPool 
    Is impersonating: False 
    Stack trace:    at System.Web.HttpForbiddenHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 
 
Custom event details:

**Comment by scrummie02** [comment]
I built hte newest version and on my pc during debug I can update posts but not the settings.  For example change the name of the blog.

**Comment by dvprez** [comment]
I'm having this problem also, but with MS SQLServer.  Can't change blogname.  Can't update settings.  Also, don't see advanced settings anywhere.  If you tell me what to look for, I'd be glad to help.

**Comment by rxtur** [comment]
I'll take a look at DB providers with latest build.

**Comment by scrummie02** [comment]
Do you need a 2012 server to test this?

Sent from Outlook




On Mon, Nov 16, 2015 at 8:13 PM -0800, "rxtur" <notifications@github.com> wrote:












I'll take a look at DB providers with latest build.

**Comment by rxtur** [comment]
No.

-----Original Message-----

**Comment by dvprez** [comment]
Don't know if this helps, this is the error I'm getting:

TypeError: Cannot read property 'OptionValue' of undefined
    at k.$scope.save (settingController.js:62)
    at angular.min.js:177
    at angular.min.js:194
    at k.$eval (angular.min.js:112)
    at k.$apply (angular.min.js:112)
    at HTMLButtonElement.<anonymous> (angular.min.js:194)
    at HTMLButtonElement.jQuery.event.dispatch (jquery-2.1.4.js:4435)
    at HTMLButtonElement.elemData.handle (jquery-2.1.4.js:4121)

**Comment by scrummie02** [comment]
Hello, where did you find that?, I didn't see it.

**Comment by dvprez** [comment]
It's the error I get in Chrome, when I press F12 and then hit the save button on the blog 

![blogsaveerror](https://cloud.githubusercontent.com/assets/15875416/11215455/45eb3d40-8d14-11e5-898f-9d939acc52f6.png)

**Comment by dvprez** [comment]
In the SettingController.js I commented out this line (Line 63) and now it's saving, But I still don't see the button for Advanced Controls on my left menu.

// $scope.settings.FacebookLanguage = $scope.selFacebookLanguage.OptionValue;

**Comment by scrummie02** [comment]
I wonder if something is amiss with the facebook portion of the comments
options?

**Comment by rxtur** [comment]
Missed empty string check while setting default values for timezone and Facebook language. Fixed with latest push.

**Comment by scrummie02** [comment]
Get the following now with the mysql web.config
Blog blog = context.Items[CONTEXT_ITEM_KEY] as Blog; 
An exception of type 'System.NullReferenceException' occurred in BlogEngine.Core.dll but was not handled in user code

Additional information: Object reference not set to an instance of an object.

**Comment by scrummie02** [comment]
Still getting an error when trying to update settings.  It works locally but not on IIS 8 on 2012.  Is there a setting I need to hit in the iis config?  It's full trust and I deployed through web deploy. 

Sent from Outlook




On Tue, Nov 17, 2015 at 6:33 PM -0800, "rxtur" <notifications@github.com> wrote:












Missed empty string check while setting default values for timezone and Facebook language. Fixed with latest push.

**Comment by scrummie02** [comment]
Never mind.  Had to delete the tables from the DB, but still having issues in IIS 8.5 and 2012

Sent from Outlook




On Tue, Nov 17, 2015 at 6:33 PM -0800, "rxtur" <notifications@github.com> wrote:












Missed empty string check while setting default values for timezone and Facebook language. Fixed with latest push.

**Comment by rxtur** [comment]
Just a note: if issue closed and you still having problem, specially if this is not exactly same problem, better to open new issue so it is visible in the list.
Also, helps to add steps to reproduce error, otherwise I assume this is clean install with no changes, run it, and don't see an error. With all the head scratching etc :)

**Comment by scrummie02** [comment]
Sure. I'll open a a new issue.  Right now it's only on IIS 8.5 and 2012 so I'm sure it's a config issue with IIS

Sent from Outlook




On Fri, Nov 20, 2015 at 3:42 PM -0800, "rxtur" <notifications@github.com> wrote:












Just a note: if issue closed and you still having problem, specially if this is not exactly same problem, better to open new issue so it is visible in the list.

Also, helps to add steps to reproduce error, otherwise I assume this is clean install with no changes, run it, and don't see an error. With all the head scratching etc :)

**Comment by syedrashid47** [comment]
Just change the App pool to Integrated
